agentic: false
audit-interval: 0
base-url: http://localhost:8000/v1
batch-size: 40
classes: organisation
critic-interval: 0
dataset-name: findok
enable-critic: false
enable-prune: false
extra-train-dir: /share/nverdha/data/bfg/final_files/2026-04-23_findok-manually-annotated_TRAIN.conllu
feedback: null
format: regex
max-counter-examples: 10
max-iterations: 10
max-rules: 20
max-samples: 50
model: Qwen/Qwen3.5-35B-A3B
no-grex: false
no-mdreport: false
num-classes: null
output: results_findok.json
pool-size: null
refine-every: 10
refine-per-batch: 1
rules-json: null
sampling-strategy: balanced
seed: 42
shots: null
skip-synthesis: false
synthesis-strategy: bulk
train-dir: /share/nverdha/data/bfg/final_files/2025-04-26_findok_train_final.conllu
train-ratio: 0.8
val-dir: /share/nverdha/data/bfg/final_files/2026-04-23_findok-manually-annotated_VALIDATE.conllu
windows: false
wrules-json: null
