agentic: false
audit-interval: 0
base-url: http://localhost:8000/v1
batch-size: 150
classes: person
critic-interval: 2
dataset-name: findok
enable-critic: true
enable-prune: false
extra-train-dir: null
feedback: reports/findok/Qwen_Qwen3.5-35B-A3B/organisation/2026-05-25/feedback.json
format: regex
max-counter-examples: 10
max-iterations: 1
max-rules: 30
max-samples: 200
model: Qwen/Qwen3.5-35B-A3B
no-grex: false
no-mdreport: false
num-classes: null
output: results_findok.json
pool-size: null
refine-every: 0
refine-per-batch: 0
resume-from: null
rules-json: reports/findok/Qwen_Qwen3.5-35B-A3B/organisation/2026-05-25/results_findok_transfer.json
sampling-strategy: balanced
seed: 42
shots: null
skip-synthesis: true
synthesis-strategy: bulk
synthesize-per-batch: true
test-dir: /share/nverdha/data/ris/corrected/ris_dev_corrected.conllu
test-name: findok
train-dir: /share/nverdha/data/bfg/corrected/findok_train_final.conllu
train-name: findok
train-ratio: 0.8
transfer-classes: null
transfer-continuation: synthesize_and_refine
transfer-dataset-name: null
transfer-name: null
transfer-test-dir: null
transfer-test-name: null
transfer-train-dir: null
windows: false
