agentic: false
audit-interval: 0
base-url: http://localhost:8000/v1
batch-size: 50
classes: person
critic-interval: 20
dataset-name: findok
enable-critic: true
enable-prune: true
extra-train-dir: null
feedback: reports/findok/Qwen_Qwen3.5-35B-A3B/person/2026-08-19_v1/feedback.json
format: regex
max-counter-examples: 10
max-iterations: 0
max-rules: 30
max-samples: 100
model: Qwen/Qwen3.5-35B-A3B
no-grex: false
no-mdreport: false
num-classes: null
output: results_ris.json
pool-size: 0
prune-with-refine: false
refine-every: 10
refine-per-batch: 1
resume-from: null
rules-json: reports/findok/Qwen_Qwen3.5-35B-A3B/person/2026-08-19_v1/results_ris_transfer_v1.json
sampling-strategy: balanced
seed: 42
shots: null
skip-synthesis: true
synthesis-strategy: bulk
synthesize-per-batch: false
test-dir: /share/nverdha/data/ris/ris_train_dev.conllu
test-name: findok
train-dir: /share/nverdha/data/ris/ris_train_training.conllu
train-name: findok
train-ratio: 0.8
transfer-classes: null
transfer-continuation: null
transfer-dataset-name: ris
transfer-name: ris
transfer-test-dir: null
transfer-test-name: null
transfer-train-dir: null
windows: false
